application: google-app-engine-django
version: 1
runtime: python
api_version: 1

handlers:
 url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /static
  static_dir: static

- url: /.*
  script: main.py
